export const USER_FETCH = "USER_FETCH";
export const USER_FETCH_PENDING = "USER_FETCH_PENDING";
export const USER_FETCH_FULFILLED = "USER_FETCH_FULFILLED";
export const USER_FETCH_REJECTED = "USER_FETCH_REJECTED";

export const USER_LOGOUT = "USER_LOGOUT";
